### ISSUE TITLE
SecurityFilter: agree on requirements and rewrite

### ISSUE THREAD

**Issue by sherriff** [Cantara/Whydah-UserIdentityBackend#12]
//Erik's thoughts so far
    //private static final String[] OPEN_PATHS = {"/health", "/authenticate/application"};
    //Suggestion to change to POST /application/authenticate

    //starts with /{applicationTokenId}: {applicationTokenId}/authenticate/user/
    // 1. Fetch applicationToken from STS
    // 2. Verify application is authorized

    //starts with /{applicationTokenId}/{userTokenId}
    // /{applicationTokenId}/{userTokenId}/user/, /{applicationTokenId}/{userTokenId}/users,
    // /{applicationTokenId}/{userTokenId}/application, /{applicationTokenId}/{userTokenId}/applications
    // 1. Fetch applicationToken from STS
    // 2. Verify application is authorized
    // 3. Fetch userTokenId from STS
    // 4. Verify user is authorized

    //Suggest to deprecate PasswordResource and use PUT on user instead.
    //Reset password should be exposed by UserAdminService.
    //a) An Administrator uses the reset password option in Whydah UserAdminWebApp (or similar) => We have a userTokenID
    // UserAdminService will send PUT request to UIB with tmp password and send email to user with reset password link

    //b) An user has forgotten his/her password from SSOLoginWebApp (or similar) => We do not have any userTokenID, only a username
    // In this scenario we can use the userTokenID of a user which represents the SSOLoginWebApp.
    //OR we skip checking the userToken. TODO Decide.

Endpoints today: 
a. Open path without authentication 
/health

b. Require authenticated and authorized applicationtokenid 
/password/{applicationtokenid}
/{applicationTokenId}/authenticate/user

c. Require authenticated and authorized applicationtokenid and userTokenId 
/{applicationtokenid}/{userTokenId}/application
/{applicationtokenid}/{userTokenId}/verifyApplicationAuth
/{applicationtokenid}/{userTokenId}/applications
/{applicationtokenid}/{usertokenid}/useraggregate
/{applicationtokenid}/{userTokenId}/user
/{applicationtokenid}/{usertokenid}/users

Delete StubbedApplicationAccessRepository?

**Comment by totto** [comment]
Where do we find the requirements?

**Comment by baardl** [comment]
For applications enable this? https://www.eff.org/deeplinks/2013/08/pushing-perfect-forward-secrecy-important-web-privacy-protection

**Comment by totto** [comment]
Fixed in 2.1.17
