### ISSUE TITLE
SecurityTokenServiceHelper should log on application

### ISSUE THREAD

**Issue by sherriff** [Cantara/Whydah-UserIdentityBackend#14]
SecurityTokenServiceHelper does not perform application logon. 
The logic for application logon and fetching of usertoken is assumed to be pretty close  to the code in TokenServiceClient in UserAdminWebapp. 

This was discovered when testing #11, but is not caused by any of the changes there afaik.

**Comment by totto** [comment]
fixed in 2.1.17
