### ISSUE TITLE
http 409 conflict must provide reason for conflict

### ISSUE THREAD

**Issue by baardl** [Cantara/Whydah-UserIdentityBackend#18]
When trying to add an new user-record 409, conflict will be thrown often.
We must provide a description of which parameter that conflicts.
See http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html section 409 for description.

**Comment by sherriff** [comment]
baardl: Can you retest/review?

**Comment by baardl** [comment]
Retested and confirmed.
