### ISSUE TITLE
Authenticate and authorize application 

### ISSUE THREAD

**Issue by sherriff** [Cantara/Whydah-UserIdentityBackend#26]

**Comment by totto** [comment]
Dependent on #27

**Comment by sherriff** [comment]
Do we have a suggested design for authentication of applications?

**Comment by totto** [comment]
STS validate appID and appSecret on application log-on today...   with 2.1 application data administered in Whydah, we will extend the verification to check IP address of caller, and to set maximum session lease time according to application data, and to select encrypted cipher for securitylevel>1 communication

**Comment by totto** [comment]
we will also be able to terminate application sessions based upon the application DEFCON erquirements defined in the application structure

**Comment by sherriff** [comment]
Misunderstanding here, Totto and I agreed to try his suggestion of letting STS perform this check. Will remove the endpoint in UIB again.
