### ISSUE TITLE
CRUD for Application using HSQLDB

### ISSUE THREAD

**Issue by totto** [Cantara/Whydah-UserIdentityBackend#27]
See https://wiki.cantara.no/display/whydah/ApplicationData

**Comment by sherriff** [comment]
This issue is too vague for me. Can you please be more concrete?

**Comment by totto** [comment]
CRUD endpoint in UIB for persistence of the datastructure examplified in wiki.... and as for now stubbed in UAS and old version stubbed in STS, as well as adjusting applications/query for new datamodell

**Comment by sherriff** [comment]
Suggestions for splitting this issue:
1. json first. XML (if ever) can come later. 
2. Reduce data model down to a minimum. We now have flyway, so extending the model later is no biggie. See Application.java for the current supported model. 
3. Is CRUD what we need? Anything more? E.g. authentication and authorization can be moved to a separate issue. 
4. Which queries do we need? -> Separate issues.

**Comment by totto** [comment]
1. JSON only (especially in UIB)
2. we would like to have an as open open modell as possible, and the JSON example in UserHelper is propably 90%
3. this is admin-functionality, but we could keep the A&A as a separate issue 
4. as a start... listApplications  (as examplified in ListApplicationsComand in Java-SDK)

**Comment by sherriff** [comment]
Decided to let SDK be responsible for Application(Data) and logic for parsing XML and Json.

**Comment by totto** [comment]
first shot at ACL-part of application:  "ACL": [{
       "applicationID": "11",[{
            "/admin/applications": [
               "READ",
               "WRITE"
           }]
       }]
    }]

**Comment by sherriff** [comment]
Consider this done. Create new issues if anything should be changed.
