### ISSUE TITLE
CONSTRETTO:  dev != DEV confursion

### ISSUE THREAD

**Issue by totto** [Cantara/Whydah-UserIdentityBackend#32]

**Comment by sherriff** [comment]
I believe the constretto tags are case sensitive. 
We can change them to DEV, if you prefer?

**Comment by totto** [comment]
could we do ignore case on contratte tags?

**Comment by sherriff** [comment]
I don't know if constretto supports this or how to configure it.

**Comment by totto** [comment]
then we should use DEV I think to be consistant
