### ISSUE TITLE
BUG: Overwirting the ApplicationId on application create.

### ISSUE THREAD

**Issue by baardl** [Cantara/Whydah-UserIdentityBackend#38]
public Application create(Application application) {
       return create(UUID.randomUUID().toString(), application);
   }
   //used by ApplicationImporter, should be remove later
   public Application create(String applicationId, Application application) {

-> should be allowed to create applicationId in webapp or remote application.

**Comment by sherriff** [comment]
incomplete. 

if (application.getId() != null) {
            return Response.status(Response.Status.BAD_REQUEST).entity("id is not allowed when creating new Application").build();
        }

**Comment by sherriff** [comment]
We do not know what to do.
