### ISSUE TITLE
New requirements for Whydah 2.1

### ISSUE THREAD

**Issue by sherriff** [Cantara/Whydah-UserIdentityBackend#7]
https://github.com/altran/_Whydah-UserIdentityBackend/issues/42

New requirements for Whydah 2.1:

Security

    minimum securitylevel
    allowed DEFCON levels
    prioritized list of crypto algorithms
    bootstrap crypto dataset

Roles

    registered application roles

API's

    Add role to application
    Add organization to application
    Add/Edit crypto algorithms for application
    Update applicationsecret for Application

And not to forget: ip/IP-range per application

**Comment by totto** [comment]
See also #27

**Comment by totto** [comment]
Fixed in 2.1.17
